version: '3.8'
services:  
  
  db:
    container_name: pg_container
    image: postgres
    restart: always
    hostname: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - ./Database:/docker-entrypoint-initdb.d/

  dbinterface:
    build:
      context: ./DatabaseInterface
    container_name: db_interface
    restart: always
    hostname: db_interface
    ports:
      - "4000:4000"
    networks:
      - backend
    depends_on:
      - db

  # pushnotification:
  #   build:
  #     context: ./PushNotification
  #   container_name: push_notification
  #   restart: always
  #   hostname: push_notification
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - backend
  #   depends_on:
  #     - dbinterface
  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - backend
    depends_on:
      - db

networks:
  backend:
    external:
      name: backend
